import type { Metadata } from "next";
import "./globals.css";
import LocalFont from "next/font/local";
import { Header } from "@/components/layout/Header";
import { getCurrentUser } from "@/helper/getCurrentUser";
import { useAuthStore } from "@/store/authStore";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const satoshi = LocalFont({
  src: "../public/font/Satoshi.ttf",
});

export const metadata: Metadata = {
  title: "Nrx",
  description: "Generated by Tobias Onandia",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${satoshi.className} antialiased min-h-screen bg-gray-900`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
