import type { Metadata } from "next";
import "./globals.css";
import LocalFont from "next/font/local";
import { Header } from "@/components/layout/Header";

const satoshi = LocalFont({
  src: "../public/font/Satoshi.ttf",
});

export const metadata: Metadata = {
  title: "Nrx",
  description: "Generated by Tobias Onandia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${satoshi.className} antialiased min-h-screen bg-gray-900`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
